tmgmt.translator.settings.oht:
  type: tmgmt.translator_base
  mapping:
    api_public_key:
      type: string
      label: OHT API Public key
    api_secret_key:
      type: string
      label: OHT API Secret key
    use_sandbox:
      type: boolean
      label: Use the sandbox
tmgmt_oht.settings:
  type: config_object
  mapping:
    tmgmt_oht_debug:
      type: boolean
      label: Debugging
